server:
  port: 8090

spring:
  datasource:
    # 使用PostgreSQL
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: zeqianliu
    password: 12345678

  mybatis-plus:
    global-config:
      db-config:
        id-type: auto
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mail:
    host: smtp.office365.com
    port: 587
    username: genesian42@outlook.com
    password: Genesian@group42
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  admin:
    email: genesian42@outlook.com

logging:
  level:
    com.au.GenesianTheatreCompany: debug

